
    // go/mss-setup#7-load-the-js-or-css-from-your-initial-page
    if(!window['_DumpException']) {
      const _DumpException = window['_DumpException'] || function(e) {
        throw e;
      };
      window['_DumpException'] = _DumpException;
    }
  "use strict";this.default_tr=this.default_tr||{};(function(_){var window=this;
try{
_._F_toggles_initialize=function(a){(typeof globalThis!=="undefined"?globalThis:typeof self!=="undefined"?self:this)._F_toggles=a||[]};(0,_._F_toggles_initialize)([0x306, ]);
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var ba,ea,sa,ya,Ba,Ca,Da,Ga,Ha,Ia,Ka,$a,kb,nb,ob,pb,w,rb,sb,ub,yb,Ab,Bb,Cb;_.aa=function(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,_.aa);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)};ba=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");_.aa.call(this,c+a[d])};ea=function(a){if(_.ca)a(_.ca);else{var b;((b=da)!=null?b:da=[]).push(a)}};_.ia=function(){!_.ca&&_.fa&&_.ha();return _.ca};
_.ha=function(){_.ca=_.fa();var a;(a=da)==null||a.forEach(ea);da=void 0};_.ka=function(a){_.ca&&ja(a)};_.ma=function(){_.ca&&la(_.ca)};_.oa=function(a,b){b.hasOwnProperty("displayName")||(b.displayName=a.toString());b[na]=a};_.pa=function(a){a&&typeof a.dispose=="function"&&a.dispose()};sa=function(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];_.qa(d)?sa.apply(null,d):_.pa(d)}};_.ua=function(a,b){return(0,_.ta)(a,b)>=0};_.va=function(a,b){_.ua(a,b)||a.push(b)};
_.wa=function(a,b){b=(0,_.ta)(a,b);var c;(c=b>=0)&&Array.prototype.splice.call(a,b,1);return c};_.xa=function(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};ya=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.qa(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};
Ba=function(a,b){b=b||a;for(var c=0,d=0,e={};d<a.length;){var f=a[d++],g=_.za(f)?"o"+_.Aa(f):(typeof f).charAt(0)+f;Object.prototype.hasOwnProperty.call(e,g)||(e[g]=!0,b[c++]=f)}b.length=c};Ca=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};Da=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ea=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
Ga=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Fa.length;f++)c=Fa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};Ha=function(a){var b=arguments.length;if(b==1&&Array.isArray(arguments[0]))return Ha.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};Ia=function(a){return{valueOf:a}.valueOf()};
Ka=function(){var a=null;if(!Ja)return a;try{var b=function(c){return c};a=Ja.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a};_.Ma=function(){La===void 0&&(La=Ka());return La};_.Oa=function(a){var b=_.Ma();return new _.Na(b?b.createScriptURL(a):a)};_.Pa=function(a){if(a instanceof _.Na)return a.g;throw Error("x");};
_.Qa=function(a,b){b=b===void 0?document:b;var c,d;b=(d=(c="document"in b?b.document:b).querySelector)==null?void 0:d.call(c,a+"[nonce]");return b==null?"":b.nonce||b.getAttribute("nonce")||""};_.Sa=function(a){var b=_.Ma();return new Ra(b?b.createScript(a):a)};_.Ta=function(a){if(a instanceof Ra)return a.g;throw Error("x");};_.Ua=function(a,b){a.src=_.Pa(b);(b=_.Qa("script",a.ownerDocument))&&a.setAttribute("nonce",b)};_.Va=function(){var a=_.t.navigator;return a&&(a=a.userAgent)?a:""};
_.v=function(a){return _.Va().indexOf(a)!=-1};_.Ya=function(){return _.Wa?!!_.Xa&&_.Xa.brands.length>0:!1};_.Za=function(){return _.Ya()?!1:_.v("Opera")};$a=function(){return _.Wa?!!_.Xa&&!!_.Xa.platform:!1};_.ab=function(){return _.v("iPhone")&&!_.v("iPod")&&!_.v("iPad")};_.bb=function(){return _.ab()||_.v("iPad")||_.v("iPod")};_.cb=function(){return $a()?_.Xa.platform==="macOS":_.v("Macintosh")};
_.eb=function(a){var b=_.db.apply(1,arguments);if(b.length===0)return _.Oa(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return _.Oa(c)};_.fb=function(a){_.t.setTimeout(function(){throw a;},0)};kb=function(){for(var a;a=gb.remove();){try{a.g.call(a.scope)}catch(b){_.fb(b)}hb(ib,a)}jb=!1};_.mb=function(a){a=_.lb(a);return _.Oa(a)};_.lb=function(a){return a===null?"null":a===void 0?"undefined":a};
nb=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};ob=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};pb=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};_.qb=pb(this);
w=function(a,b){if(b)a:{var c=_.qb;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ob(c,a,{configurable:!0,writable:!0,value:b})}};
w("Symbol",function(a){if(a)return a;var b=function(f,g){this.g=f;ob(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("b");return new b(c+(f||"")+"_"+d++,f)};return e});
w("Symbol.iterator",function(a){if(a)return a;a=Symbol("c");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=_.qb[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&ob(d.prototype,a,{configurable:!0,writable:!0,value:function(){return rb(nb(this))}})}return a});rb=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
sb=typeof Object.create=="function"?Object.create:function(a){var b=function(){};b.prototype=a;return new b};
_.tb=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if(typeof Reflect!="undefined"&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){e===void 0&&(e=c);e=sb(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();
if(typeof Object.setPrototypeOf=="function")ub=Object.setPrototypeOf;else{var vb;a:{var wb={a:!0},xb={};try{xb.__proto__=wb;vb=xb.a;break a}catch(a){}vb=!1}ub=vb?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("d`"+a);return a}:null}yb=ub;
_.x=function(a,b){a.prototype=sb(b.prototype);a.prototype.constructor=a;if(yb)yb(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.O=b.prototype};_.y=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:nb(a)};throw Error("e`"+String(a));};
_.zb=function(a){if(!(a instanceof Array)){a=_.y(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a};_.z=function(a){return Ab(a,a)};Ab=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a};Bb=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};Cb=typeof Object.assign=="function"?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Bb(d,e)&&(a[e]=d[e])}return a};
w("Object.assign",function(a){return a||Cb});_.db=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};w("Reflect",function(a){return a?a:{}});w("Reflect.construct",function(){return _.tb});w("Reflect.setPrototypeOf",function(a){return a?a:yb?function(b,c){try{return yb(b,c),!0}catch(d){return!1}}:null});
w("Promise",function(a){function b(){this.g=null}function c(g){return g instanceof e?g:new e(function(h){h(g)})}if(a)return a;b.prototype.h=function(g){if(this.g==null){this.g=[];var h=this;this.j(function(){h.o()})}this.g.push(g)};var d=_.qb.setTimeout;b.prototype.j=function(g){d(g,0)};b.prototype.o=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var l=g[h];g[h]=null;try{l()}catch(m){this.l(m)}}}this.g=null};b.prototype.l=function(g){this.j(function(){throw g;
})};var e=function(g){this.g=0;this.j=void 0;this.h=[];this.A=!1;var h=this.l();try{g(h.resolve,h.reject)}catch(l){h.reject(l)}};e.prototype.l=function(){function g(m){return function(n){l||(l=!0,m.call(h,n))}}var h=this,l=!1;return{resolve:g(this.K),reject:g(this.o)}};e.prototype.K=function(g){if(g===this)this.o(new TypeError("h"));else if(g instanceof e)this.N(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.G(g):this.s(g)}};e.prototype.G=
function(g){var h=void 0;try{h=g.then}catch(l){this.o(l);return}typeof h=="function"?this.oa(h,g):this.s(g)};e.prototype.o=function(g){this.B(2,g)};e.prototype.s=function(g){this.B(1,g)};e.prototype.B=function(g,h){if(this.g!=0)throw Error("i`"+g+"`"+h+"`"+this.g);this.g=g;this.j=h;this.g===2&&this.H();this.F()};e.prototype.H=function(){var g=this;d(function(){if(g.D()){var h=_.qb.console;typeof h!=="undefined"&&h.error(g.j)}},1)};e.prototype.D=function(){if(this.A)return!1;var g=_.qb.CustomEvent,
h=_.qb.Event,l=_.qb.dispatchEvent;if(typeof l==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=_.qb.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.j;return l(g)};e.prototype.F=function(){if(this.h!=null){for(var g=0;g<this.h.length;++g)f.h(this.h[g]);this.h=null}};var f=new b;e.prototype.N=function(g){var h=this.l();g.Ld(h.resolve,
h.reject)};e.prototype.oa=function(g,h){var l=this.l();try{g.call(h,l.resolve,l.reject)}catch(m){l.reject(m)}};e.prototype.then=function(g,h){function l(q,r){return typeof q=="function"?function(u){try{m(q(u))}catch(C){n(C)}}:r}var m,n,p=new e(function(q,r){m=q;n=r});this.Ld(l(g,m),l(h,n));return p};e.prototype.catch=function(g){return this.then(void 0,g)};e.prototype.Ld=function(g,h){function l(){switch(m.g){case 1:g(m.j);break;case 2:h(m.j);break;default:throw Error("j`"+m.g);}}var m=this;this.h==
null?f.h(l):this.h.push(l);this.A=!0};e.resolve=c;e.reject=function(g){return new e(function(h,l){l(g)})};e.race=function(g){return new e(function(h,l){for(var m=_.y(g),n=m.next();!n.done;n=m.next())c(n.value).Ld(h,l)})};e.all=function(g){var h=_.y(g),l=h.next();return l.done?c([]):new e(function(m,n){function p(u){return function(C){q[u]=C;r--;r==0&&m(q)}}var q=[],r=0;do q.push(void 0),r++,c(l.value).Ld(p(q.length-1),n),l=h.next();while(!l.done)})};return e});
var Db=function(a,b,c){if(a==null)throw new TypeError("k`"+c);if(b instanceof RegExp)throw new TypeError("l`"+c);return a+""};w("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=Db(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});w("Object.setPrototypeOf",function(a){return a||yb});w("Symbol.dispose",function(a){return a?a:Symbol("m")});
w("WeakMap",function(a){function b(){}function c(l){var m=typeof l;return m==="object"&&l!==null||m==="function"}function d(l){if(!Bb(l,f)){var m=new b;ob(l,f,{value:m})}}function e(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,3]]);if(n.get(l)!=2||n.get(m)!=3)return!1;n.delete(l);n.set(m,4);return!n.has(l)&&n.get(m)==4}catch(p){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var g=0,h=function(l){this.g=(g+=Math.random()+1).toString();if(l){l=_.y(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}};h.prototype.set=function(l,m){if(!c(l))throw Error("n");d(l);if(!Bb(l,f))throw Error("o`"+l);l[f][this.g]=m;return this};h.prototype.get=function(l){return c(l)&&Bb(l,f)?l[f][this.g]:void 0};h.prototype.has=function(l){return c(l)&&Bb(l,f)&&Bb(l[f],this.g)};h.prototype.delete=function(l){return c(l)&&
Bb(l,f)&&Bb(l[f],this.g)?delete l[f][this.g]:!1};return h});
w("Map",function(a){if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),l=new a(_.y([[h,"s"]]));if(l.get(h)!="s"||l.size!=1||l.get({x:4})||l.set({x:4},"t")!=l||l.size!=2)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=4||n.value[1]!="t"||!m.next().done?!1:!0}catch(p){return!1}}())return a;var b=new WeakMap,c=function(h){this[0]={};this[1]=
f();this.size=0;if(h){h=_.y(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}};c.prototype.set=function(h,l){h=h===0?0:h;var m=d(this,h);m.list||(m.list=this[0][m.id]=[]);m.Ga?m.Ga.value=l:(m.Ga={next:this[1],zb:this[1].zb,head:this[1],key:h,value:l},m.list.push(m.Ga),this[1].zb.next=m.Ga,this[1].zb=m.Ga,this.size++);return this};c.prototype.delete=function(h){h=d(this,h);return h.Ga&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],h.Ga.zb.next=h.Ga.next,h.Ga.next.zb=
h.Ga.zb,h.Ga.head=null,this.size--,!0):!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].zb=f();this.size=0};c.prototype.has=function(h){return!!d(this,h).Ga};c.prototype.get=function(h){return(h=d(this,h).Ga)&&h.value};c.prototype.entries=function(){return e(this,function(h){return[h.key,h.value]})};c.prototype.keys=function(){return e(this,function(h){return h.key})};c.prototype.values=function(){return e(this,function(h){return h.value})};c.prototype.forEach=function(h,l){for(var m=this.entries(),
n;!(n=m.next()).done;)n=n.value,h.call(l,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(h,l){var m=l&&typeof l;m=="object"||m=="function"?b.has(l)?m=b.get(l):(m=""+ ++g,b.set(l,m)):m="p_"+l;var n=h[0][m];if(n&&Bb(h[0],m))for(h=0;h<n.length;h++){var p=n[h];if(l!==l&&p.key!==p.key||l===p.key)return{id:m,list:n,index:h,Ga:p}}return{id:m,list:n,index:-1,Ga:void 0}},e=function(h,l){var m=h[1];return rb(function(){if(m){for(;m.head!=h[1];)m=m.zb;for(;m.next!=m.head;)return m=
m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})},f=function(){var h={};return h.zb=h.next=h.head=h},g=0;return c});
w("Set",function(a){if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(_.y([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||f.value[0].x!=4||f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;var b=function(c){this.g=new Map;if(c){c=
_.y(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size};b.prototype.add=function(c){c=c===0?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(f){return c.call(d,f,f,e)})};return b});w("globalThis",function(a){return a||_.qb});var Eb=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
w("Array.prototype.entries",function(a){return a?a:function(){return Eb(this,function(b,c){return[b,c]})}});w("Array.prototype.keys",function(a){return a?a:function(){return Eb(this,function(b){return b})}});w("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=Db(this,b,"endsWith");c===void 0&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;e>0&&c>0;)if(d[--c]!=b[--e])return!1;return e<=0}});
w("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});w("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});w("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Bb(b,d)&&c.push([d,b[d]]);return c}});
w("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});w("Array.prototype.values",function(a){return a?a:function(){return Eb(this,function(b,c){return c})}});
w("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Bb(b,d)&&c.push(b[d]);return c}});w("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});w("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
w("String.prototype.includes",function(a){return a?a:function(b,c){return Db(this,b,"includes").indexOf(b,c||0)!==-1}});w("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});w("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});w("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});w("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
w("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});w("Object.getOwnPropertySymbols",function(a){return a?a:function(){return[]}});
w("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("p");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});w("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;c<0&&(c=Math.max(0,e+c));if(d==null||d>e)d=e;d=Number(d);d<0&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});
var Fb=function(a){return a?a:Array.prototype.fill};w("Int8Array.prototype.fill",Fb);w("Uint8Array.prototype.fill",Fb);w("Uint8ClampedArray.prototype.fill",Fb);w("Int16Array.prototype.fill",Fb);w("Uint16Array.prototype.fill",Fb);w("Int32Array.prototype.fill",Fb);w("Uint32Array.prototype.fill",Fb);w("Float32Array.prototype.fill",Fb);w("Float64Array.prototype.fill",Fb);
w("Promise.prototype.finally",function(a){return a?a:function(b){return this.then(function(c){return Promise.resolve(b()).then(function(){return c})},function(c){return Promise.resolve(b()).then(function(){throw c;})})}});w("Array.prototype.flat",function(a){return a?a:function(b){b=b===void 0?1:b;var c=[];Array.prototype.forEach.call(this,function(d){Array.isArray(d)&&b>0?(d=Array.prototype.flat.call(d,b-1),c.push.apply(c,d)):c.push(d)});return c}});
_._DumpException=window._DumpException||function(a){throw a;};window._DumpException=_._DumpException;var Gb,Hb,Ib,Kb,Jb,Nb,Ob,Pb,Qb;Gb=Gb||{};_.t=this||self;Hb=_.t._F_toggles||[];Ib=/^[a-zA-Z_$][a-zA-Z0-9._$]*$/;Kb=function(a){if(typeof a!=="string"||!a||a.search(Ib)==-1)throw Error("q");if(!Jb||Jb.type!="goog")throw Error("r`"+a);if(Jb.Jk)throw Error("s");Jb.Jk=a};Kb.get=function(){return null};Jb=null;_.Lb=function(a,b){a=a.split(".");b=b||_.t;for(var c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b};
_.Mb=function(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"};_.qa=function(a){var b=_.Mb(a);return b=="array"||b=="object"&&typeof a.length=="number"};_.za=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"};_.Aa=function(a){return Object.prototype.hasOwnProperty.call(a,Nb)&&a[Nb]||(a[Nb]=++Ob)};Nb="closure_uid_"+(Math.random()*1E9>>>0);Ob=0;Pb=function(a,b,c){return a.call.apply(a.bind,arguments)};
Qb=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};_.A=function(a,b,c){_.A=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?Pb:Qb;return _.A.apply(null,arguments)};
_.Rb=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};_.Sb=function(){return Date.now()};_.Tb=function(a,b){a=a.split(".");var c=_.t;a[0]in c||typeof c.execScript=="undefined"||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||b===void 0?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};
_.B=function(a,b){function c(){}c.prototype=b.prototype;a.O=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.on=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};_.B(_.aa,Error);_.aa.prototype.name="CustomError";var Ub;_.B(ba,_.aa);ba.prototype.name="AssertionError";var da;var D=function(a,b){this.h=a;this.g=b||null};D.prototype.toString=function(){return this.h};new D("z72MOc","z72MOc");new D("IW8Usd");new D("jbDgG");new D("hdXIif");new D("DFElXb");new D("ZtVrH");_.Vb=new D("rJmJrc","rJmJrc");new D("fJuxOc");new D("JccZRe");new D("vk3Wc");new D("IykvEf");new D("NGntwf");new D("FENZqe");new D("ofuapc");new D("BWETze");new D("ZmXAm");_.Wb=new D("n73qwf","n73qwf");var na=Symbol("u");_.E=function(){this.Ca=this.Ca;this.oa=this.oa};_.E.prototype.Ca=!1;_.E.prototype.fb=function(){return this.Ca};_.E.prototype.dispose=function(){this.Ca||(this.Ca=!0,this.I())};_.E.prototype[Symbol.dispose]=function(){this.dispose()};_.E.prototype.I=function(){if(this.oa)for(;this.oa.length;)this.oa.shift()()};var ac;_.ta=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.Xb=Array.prototype.lastIndexOf?function(a,b){return Array.prototype.lastIndexOf.call(a,b,a.length-1)}:function(a,b){var c=a.length-1;c<0&&(c=Math.max(0,a.length+c));if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.lastIndexOf(b,c);for(;c>=0;c--)if(c in a&&a[c]===b)return c;return-1};_.Yb=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a==="string"?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Zb=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f=typeof a==="string"?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d};_.$b=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=typeof a==="string"?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
ac=Array.prototype.reduce?function(a,b,c){Array.prototype.reduce.call(a,b,c)}:function(a,b,c){var d=c;(0,_.Yb)(a,function(e,f){d=b.call(void 0,d,e,f,a)})};_.bc=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};_.cc=function(a,b){this.width=a;this.height=b};_.dc=function(a,b){return a==b?!0:a&&b?a.width==b.width&&a.height==b.height:!1};_.cc.prototype.aspectRatio=function(){return this.width/this.height};_.cc.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};_.cc.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.cc.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Fa;Fa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.ec=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};_.fc=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var gc=globalThis.trustedTypes,Ja=gc,La;_.Na=function(a){this.g=a};_.Na.prototype.toString=function(){return this.g+""};_.hc=Ia(function(){return typeof URL==="function"});_.ic=function(a){this.g=a};_.ic.prototype.toString=function(){return this.g+""};_.jc=Ia(function(){return new _.ic(gc?gc.emptyHTML:"")});var Ra=function(a){this.g=a};Ra.prototype.toString=function(){return this.g+""};var kc=function(a,b){this.name=a;this.value=b};kc.prototype.toString=function(){return this.name};_.lc=[new kc("OFF",Infinity),new kc("SHOUT",1200),new kc("SEVERE",1E3),new kc("WARNING",900),new kc("INFO",800),new kc("CONFIG",700),new kc("FINE",500),new kc("FINER",400),new kc("FINEST",300),new kc("ALL",0)];_.mc=function(a){return encodeURIComponent(String(a))};_.nc=function(a){return decodeURIComponent(a.replace(/\+/g," "))};_.oc=function(){return Math.floor(Math.random()*2147483648).toString(36)+Math.abs(Math.floor(Math.random()*2147483648)^_.Sb()).toString(36)};var pc=!!(Hb[0]&1024);var qc;if(Hb[0]&512)qc=pc;else{var rc=_.Lb("WIZ_global_data.oxN3nb"),sc=rc&&rc[610401301];qc=sc!=null?sc:!1}_.Wa=qc;var tc;tc=_.t.navigator;_.Xa=tc?tc.userAgentData||null:null;_.uc=function(a){_.uc[" "](a);return a};_.uc[" "]=function(){};var Ic;_.vc=_.Za();_.wc=_.Ya()?!1:_.v("Trident")||_.v("MSIE");_.xc=_.v("Edge");_.yc=_.v("Gecko")&&!(_.Va().toLowerCase().indexOf("webkit")!=-1&&!_.v("Edge"))&&!(_.v("Trident")||_.v("MSIE"))&&!_.v("Edge");_.zc=_.Va().toLowerCase().indexOf("webkit")!=-1&&!_.v("Edge");_.Ac=_.zc&&_.v("Mobile");_.Bc=_.cb();_.Cc=$a()?_.Xa.platform==="Windows":_.v("Windows");_.Dc=$a()?_.Xa.platform==="Android":_.v("Android");_.Ec=_.ab();_.Fc=_.v("iPad");_.Gc=_.v("iPod");_.Hc=_.bb();
a:{var Jc="",Kc=function(){var a=_.Va();if(_.yc)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.xc)return/Edge\/([\d\.]+)/.exec(a);if(_.wc)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.zc)return/WebKit\/(\S+)/.exec(a);if(_.vc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Kc&&(Jc=Kc?Kc[1]:"");if(_.wc){var Lc,Mc=_.t.document;Lc=Mc?Mc.documentMode:void 0;if(Lc!=null&&Lc>parseFloat(Jc)){Ic=String(Lc);break a}}Ic=Jc}_.Nc=Ic;var Oc="ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR NOBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER ACRONYM BASEFONT BIG DIR HGROUP STRIKE TT".split(" "),
Pc=[["A",new Map([["href",{ya:2}]])],["AREA",new Map([["href",{ya:2}]])],["LINK",new Map([["href",{ya:5,conditions:new Map([["rel",new Set("alternate author bookmark canonical cite help icon license next prefetch dns-prefetch prerender preconnect preload prev search subresource".split(" "))]])}]])],["SOURCE",new Map([["src",{ya:5}],["srcset",{ya:6}]])],["IMG",new Map([["src",{ya:5}],["srcset",{ya:6}]])],["VIDEO",new Map([["src",{ya:5}]])],["AUDIO",new Map([["src",{ya:5}]])]],Qc="title aria-atomic aria-autocomplete aria-busy aria-checked aria-current aria-disabled aria-dropeffect aria-expanded aria-haspopup aria-hidden aria-invalid aria-label aria-level aria-live aria-multiline aria-multiselectable aria-orientation aria-posinset aria-pressed aria-readonly aria-relevant aria-required aria-selected aria-setsize aria-sort aria-valuemax aria-valuemin aria-valuenow aria-valuetext alt align autocapitalize autocomplete autocorrect autofocus autoplay bgcolor border cellpadding cellspacing checked color cols colspan controls datetime disabled download draggable enctype face formenctype frameborder height hreflang hidden ismap label lang loop max maxlength media minlength min multiple muted nonce open placeholder preload rel required reversed role rows rowspan selected shape size sizes slot span spellcheck start step summary translate type valign value width wrap itemscope itemtype itemid itemprop itemref".split(" "),
Rc=[["dir",{ya:3,conditions:Ia(function(){return new Map([["dir",new Set(["auto","ltr","rtl"])]])})}],["async",{ya:3,conditions:Ia(function(){return new Map([["async",new Set(["async"])]])})}],["cite",{ya:2}],["loading",{ya:3,conditions:Ia(function(){return new Map([["loading",new Set(["eager","lazy"])]])})}],["poster",{ya:2}],["target",{ya:3,conditions:Ia(function(){return new Map([["target",new Set(["_self","_blank"])]])})}]],Sc=new function(a,b,c){var d=new Set(["data-","aria-"]),e=new Map(Pc);
this.j=a;this.g=e;this.l=b;this.o=c;this.h=d}(new Set(Ia(function(){return Oc.concat("STYLE TITLE INPUT TEXTAREA BUTTON LABEL".split(" "))})),new Set(Ia(function(){return Qc.concat(["class","id","tabindex","contenteditable","name"])})),new Map(Ia(function(){return Rc.concat([["style",{ya:1}]])})));var Tc;Tc=function(){this.g=Sc};_.Uc=Ia(function(){return new Tc});var $c,Zc,dd;_.Xc=function(a){return a?new _.Vc(_.Wc(a)):Ub||(Ub=new _.Vc)};_.Yc=function(a,b){return typeof b==="string"?a.getElementById(b):b};$c=function(a,b){_.ec(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:Zc.hasOwnProperty(d)?a.setAttribute(Zc[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})};
Zc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};_.ad=function(a){a=a.document;a=a.compatMode=="CSS1Compat"?a.documentElement:a.body;return new _.cc(a.clientWidth,a.clientHeight)};_.bd=function(a){return a?a.defaultView:window};
_.ed=function(a,b){var c=b[1],d=_.cd(a,String(b[0]));c&&(typeof c==="string"?d.className=c:Array.isArray(c)?d.className=c.join(" "):$c(d,c));b.length>2&&dd(a,d,b,2);return d};
dd=function(a,b,c,d){function e(h){h&&b.appendChild(typeof h==="string"?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];if(!_.qa(f)||_.za(f)&&f.nodeType>0)e(f);else{a:{if(f&&typeof f.length=="number"){if(_.za(f)){var g=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){g=typeof f.item=="function";break a}}g=!1}_.Yb(g?_.xa(f):f,e)}}};_.cd=function(a,b){b=String(b);a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)};
_.fd=function(a,b){dd(_.Wc(a),a,arguments,1)};_.gd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.hd=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};_.id=function(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.Wc=function(a){return a.nodeType==9?a:a.ownerDocument||a.document};
_.jd=function(a,b){if("textContent"in a)a.textContent=b;else if(a.nodeType==3)a.data=String(b);else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else _.gd(a),a.appendChild(_.Wc(a).createTextNode(String(b)))};_.Vc=function(a){this.g=a||_.t.document||document};_.k=_.Vc.prototype;_.k.C=function(a){return _.Yc(this.g,a)};_.k.getElementsByTagName=function(a,b){return(b||this.g).getElementsByTagName(String(a))};
_.k.R=function(a,b,c){return _.ed(this.g,arguments)};_.k.createElement=function(a){return _.cd(this.g,a)};_.k.appendChild=function(a,b){a.appendChild(b)};_.k.append=_.fd;_.k.canHaveChildren=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
_.k.Pf=_.gd;_.k.removeNode=_.hd;_.k.contains=_.id;_.k.Fc=_.jd;var kd=function(){this.id="b"};kd.prototype.toString=function(){return this.id};_.ld=function(a,b){this.type=a instanceof kd?String(a):a;this.currentTarget=this.target=b;this.defaultPrevented=this.jd=!1};_.ld.prototype.stopPropagation=function(){this.jd=!0};_.ld.prototype.preventDefault=function(){this.defaultPrevented=!0};var md=function(){if(!_.t.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};_.t.addEventListener("test",c,b);_.t.removeEventListener("test",c,b)}catch(d){}return a}();_.nd=function(a,b){_.ld.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.Of=!1;this.pointerId=0;this.pointerType="";this.timeStamp=0;this.xb=null;a&&this.zf(a,b)};_.B(_.nd,_.ld);
_.nd.prototype.zf=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.offsetX=_.zc||a.offsetX!==void 0?a.offsetX:a.layerX,this.offsetY=
_.zc||a.offsetY!==void 0?a.offsetY:a.layerY,this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Of=_.Bc?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;
this.state=a.state;this.timeStamp=a.timeStamp;this.xb=a;a.defaultPrevented&&_.nd.O.preventDefault.call(this)};_.nd.prototype.stopPropagation=function(){_.nd.O.stopPropagation.call(this);this.xb.stopPropagation?this.xb.stopPropagation():this.xb.cancelBubble=!0};_.nd.prototype.preventDefault=function(){_.nd.O.preventDefault.call(this);var a=this.xb;a.preventDefault?a.preventDefault():a.returnValue=!1};var od;od="closure_listenable_"+(Math.random()*1E6|0);_.pd=function(a){return!(!a||!a[od])};var qd=0;var rd=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.ee=e;this.key=++qd;this.kd=this.Kd=!1},sd=function(a){a.kd=!0;a.listener=null;a.proxy=null;a.src=null;a.ee=null};var td=function(a){this.src=a;this.g={};this.h=0},vd;td.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var g=ud(a,b,d,e);g>-1?(b=a[g],c||(b.Kd=!1)):(b=new rd(b,this.src,f,!!d,e),b.Kd=c,a.push(b));return b};td.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.g))return!1;var e=this.g[a];b=ud(e,b,c,d);return b>-1?(sd(e[b]),Array.prototype.splice.call(e,b,1),e.length==0&&(delete this.g[a],this.h--),!0):!1};
vd=function(a,b){var c=b.type;if(!(c in a.g))return!1;var d=_.wa(a.g[c],b);d&&(sd(b),a.g[c].length==0&&(delete a.g[c],a.h--));return d};_.wd=function(a){var b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,sd(d[e]);delete a.g[c];a.h--}};td.prototype.Xc=function(a,b,c,d){a=this.g[a.toString()];var e=-1;a&&(e=ud(a,b,c,d));return e>-1?a[e]:null};
td.prototype.hasListener=function(a,b){var c=a!==void 0,d=c?a.toString():"",e=b!==void 0;return Ca(this.g,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&f[g].capture!=b))return!0;return!1})};var ud=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.kd&&f.listener==b&&f.capture==!!c&&f.ee==d)return e}return-1};var xd,yd,zd,Cd,Ed,Fd,Gd,Jd,Bd;xd="closure_lm_"+(Math.random()*1E6|0);yd={};zd=0;_.G=function(a,b,c,d,e){if(d&&d.once)return _.Ad(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)_.G(a,b[f],c,d,e);return null}c=Bd(c);return _.pd(a)?a.J(b,c,_.za(d)?!!d.capture:!!d,e):Cd(a,b,c,!1,d,e)};
Cd=function(a,b,c,d,e,f){if(!b)throw Error("z");var g=_.za(e)?!!e.capture:!!e,h=_.Dd(a);h||(a[xd]=h=new td(a));c=h.add(b,c,d,g,f);if(c.proxy)return c;d=Ed();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)md||(e=g),e===void 0&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Fd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("A");zd++;return c};Ed=function(){var a=Gd,b=function(c){return a.call(b.src,b.listener,c)};return b};
_.Ad=function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)_.Ad(a,b[f],c,d,e);return null}c=Bd(c);return _.pd(a)?a.Mb(b,c,_.za(d)?!!d.capture:!!d,e):Cd(a,b,c,!0,d,e)};_.Hd=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)_.Hd(a,b[f],c,d,e);else d=_.za(d)?!!d.capture:!!d,c=Bd(c),_.pd(a)?a.gb(b,c,d,e):a&&(a=_.Dd(a))&&(b=a.Xc(b,c,d,e))&&_.Id(b)};
_.Id=function(a){if(typeof a==="number"||!a||a.kd)return!1;var b=a.src;if(_.pd(b))return vd(b.Ya,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Fd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);zd--;(c=_.Dd(b))?(vd(c,a),c.h==0&&(c.src=null,b[xd]=null)):sd(a);return!0};Fd=function(a){return a in yd?yd[a]:yd[a]="on"+a};
Gd=function(a,b){if(a.kd)a=!0;else{b=new _.nd(b,this);var c=a.listener,d=a.ee||a.src;a.Kd&&_.Id(a);a=c.call(d,b)}return a};_.Dd=function(a){a=a[xd];return a instanceof td?a:null};Jd="__closure_events_fn_"+(Math.random()*1E9>>>0);Bd=function(a){if(typeof a==="function")return a;a[Jd]||(a[Jd]=function(b){return a.handleEvent(b)});return a[Jd]};_.I=function(){_.E.call(this);this.Ya=new td(this);this.aj=this;this.we=null};_.B(_.I,_.E);_.I.prototype[od]=!0;_.k=_.I.prototype;_.k.Ce=function(a){this.we=a};_.k.addEventListener=function(a,b,c,d){_.G(this,a,b,c,d)};_.k.removeEventListener=function(a,b,c,d){_.Hd(this,a,b,c,d)};
_.k.dispatchEvent=function(a){var b,c=this.we;if(c)for(b=[];c;c=c.we)b.push(c);c=this.aj;var d=a.type||a;if(typeof a==="string")a=new _.ld(a,c);else if(a instanceof _.ld)a.target=a.target||c;else{var e=a;a=new _.ld(d,c);Ga(a,e)}e=!0;var f;if(b)for(f=b.length-1;!a.jd&&f>=0;f--){var g=a.currentTarget=b[f];e=Kd(g,d,!0,a)&&e}a.jd||(g=a.currentTarget=c,e=Kd(g,d,!0,a)&&e,a.jd||(e=Kd(g,d,!1,a)&&e));if(b)for(f=0;!a.jd&&f<b.length;f++)g=a.currentTarget=b[f],e=Kd(g,d,!1,a)&&e;return e};
_.k.I=function(){_.I.O.I.call(this);this.Ya&&_.wd(this.Ya);this.we=null};_.k.J=function(a,b,c,d){return this.Ya.add(String(a),b,!1,c,d)};_.k.Mb=function(a,b,c,d){return this.Ya.add(String(a),b,!0,c,d)};_.k.gb=function(a,b,c,d){return this.Ya.remove(String(a),b,c,d)};var Kd=function(a,b,c,d){b=a.Ya.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.kd&&g.capture==c){var h=g.listener,l=g.ee||g.src;g.Kd&&vd(a.Ya,g);e=h.call(l,d)!==!1&&e}}return e&&!d.defaultPrevented};
_.I.prototype.Xc=function(a,b,c,d){return this.Ya.Xc(String(a),b,c,d)};_.I.prototype.hasListener=function(a,b){return this.Ya.hasListener(a!==void 0?String(a):void 0,b)};var Ld=function(a){_.I.call(this);this.g=a||window;this.h=_.G(this.g,"resize",this.l,!1,this);this.j=_.ad(this.g||window)};_.B(Ld,_.I);Ld.prototype.I=function(){Ld.O.I.call(this);this.h&&(_.Id(this.h),this.h=null);this.j=this.g=null};Ld.prototype.l=function(){var a=_.ad(this.g||window);_.dc(a,this.j)||(this.j=a,this.dispatchEvent("resize"))};var Md=function(a){_.I.call(this);this.j=a?a.g.defaultView:window;this.o=this.j.devicePixelRatio>=1.5?2:1;this.h=(0,_.A)(this.s,this);this.l=null;(this.g=this.j.matchMedia?this.j.matchMedia("(min-resolution: 1.5dppx), (-webkit-min-device-pixel-ratio: 1.5)"):null)&&typeof this.g.addListener!=="function"&&typeof this.g.addEventListener!=="function"&&(this.g=null)};_.B(Md,_.I);
Md.prototype.start=function(){var a=this;this.g&&(typeof this.g.addEventListener==="function"?(this.g.addEventListener("change",this.h),this.l=function(){a.g.removeEventListener("change",a.h)}):(this.g.addListener(this.h),this.l=function(){a.g.removeListener(a.h)}))};Md.prototype.s=function(){var a=this.j.devicePixelRatio>=1.5?2:1;this.o!=a&&(this.o=a,this.dispatchEvent("a"))};Md.prototype.I=function(){this.l&&this.l();Md.O.I.call(this)};var Nd=function(a,b){_.E.call(this);this.o=a;if(b){if(this.l)throw Error("B");this.l=b;this.h=_.Xc(b);this.g=new Ld(_.bd(b));this.g.Ce(this.o.h());this.j=new Md(this.h);this.j.start()}};_.B(Nd,_.E);Nd.prototype.I=function(){this.h=this.l=null;this.g&&(this.g.dispose(),this.g=null);_.pa(this.j);this.j=null};_.oa(_.Wb,Nd);Kb=Kb||{};var Od=function(){_.E.call(this)};_.B(Od,_.E);Od.prototype.initialize=function(){};var Pd=function(a,b){this.g=a;this.h=b};Pd.prototype.execute=function(a){this.g&&(this.g.call(this.h||null,a),this.g=this.h=null)};Pd.prototype.abort=function(){this.h=this.g=null};var Qd=function(a,b){_.E.call(this);this.h=a;this.s=b;this.o=[];this.l=[];this.j=[]};_.B(Qd,_.E);Qd.prototype.A=Od;Qd.prototype.g=null;Qd.prototype.Za=function(){return this.s};var Rd=function(a,b){a.l.push(new Pd(b))};Qd.prototype.onLoad=function(a){var b=new this.A;b.initialize(a());this.g=b;b=(b=!!Sd(this.j,a()))||!!Sd(this.o,a());b||(this.l.length=0);return b};Qd.prototype.Jf=function(a){(a=Sd(this.l,a))&&_.fb(Error("C`"+a));this.j.length=0;this.o.length=0};
var Sd=function(a,b){for(var c=[],d=0;d<a.length;d++)try{a[d].execute(b)}catch(e){_.fb(e),c.push(e)}a.length=0;return c.length?c:null};Qd.prototype.I=function(){Qd.O.I.call(this);_.pa(this.g)};var Td=function(){this.B=this.Ca=null};_.k=Td.prototype;_.k.Yh=function(){};_.k.Yf=function(){};_.k.Uh=function(){throw Error("E");};_.k.Ug=function(){return this.Ca};_.k.Zf=function(a){this.Ca=a};_.k.isActive=function(){return!1};_.k.vh=function(){return!1};_.k.Sh=function(){};var Ud=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};var Vd=function(a,b){this.l=a;this.j=b;this.h=0;this.g=null};Vd.prototype.get=function(){if(this.h>0){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.l();return a};var hb=function(a,b){a.j(b);a.h<100&&(a.h++,b.next=a.g,a.g=b)};var Wd=function(){this.h=this.g=null};Wd.prototype.add=function(a,b){var c=ib.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};Wd.prototype.remove=function(){var a=null;this.g&&(a=this.g,this.g=this.g.next,this.g||(this.h=null),a.next=null);return a};var ib=new Vd(function(){return new Xd},function(a){return a.reset()}),Xd=function(){this.next=this.scope=this.g=null};Xd.prototype.set=function(a,b){this.g=a;this.scope=b;this.next=null};
Xd.prototype.reset=function(){this.next=this.scope=this.g=null};var Yd,jb=!1,gb=new Wd,$d=function(a,b){Yd||Zd();jb||(Yd(),jb=!0);gb.add(a,b)},Zd=function(){var a=Promise.resolve(void 0);Yd=function(){a.then(kb)}};_.ae=function(){};var be=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var ee,oe,me,ke,le,qe,pe,re;_.de=function(a){this.g=0;this.A=void 0;this.l=this.h=this.j=null;this.o=this.s=!1;if(a!=_.ae)try{var b=this;a.call(void 0,function(c){_.ce(b,2,c)},function(c){_.ce(b,3,c)})}catch(c){_.ce(this,3,c)}};ee=function(){this.next=this.j=this.h=this.l=this.g=null;this.o=!1};ee.prototype.reset=function(){this.j=this.h=this.l=this.g=null;this.o=!1};var fe=new Vd(function(){return new ee},function(a){a.reset()}),ge=function(a,b,c){var d=fe.get();d.l=a;d.h=b;d.j=c;return d};
_.de.prototype.then=function(a,b,c){return he(this,Ud(typeof a==="function"?a:null),Ud(typeof b==="function"?b:null),c)};_.de.prototype.$goog_Thenable=!0;_.de.prototype.B=function(a,b){return he(this,null,Ud(a),b)};_.de.prototype.catch=_.de.prototype.B;_.de.prototype.cancel=function(a){if(this.g==0){var b=new _.ie(a);$d(function(){je(this,b)},this)}};
var je=function(a,b){if(a.g==0)if(a.j){var c=a.j;if(c.h){for(var d=0,e=null,f=null,g=c.h;g&&(g.o||(d++,g.g==a&&(e=g),!(e&&d>1)));g=g.next)e||(f=g);e&&(c.g==0&&d==1?je(c,b):(f?(d=f,d.next==c.l&&(c.l=d),d.next=d.next.next):ke(c),le(c,e,3,b)))}a.j=null}else _.ce(a,3,b)},ne=function(a,b){a.h||a.g!=2&&a.g!=3||me(a);a.l?a.l.next=b:a.h=b;a.l=b},he=function(a,b,c,d){var e=ge(null,null,null);e.g=new _.de(function(f,g){e.l=b?function(h){try{var l=b.call(d,h);f(l)}catch(m){g(m)}}:f;e.h=c?function(h){try{var l=
c.call(d,h);l===void 0&&h instanceof _.ie?g(h):f(l)}catch(m){g(m)}}:g});e.g.j=a;ne(a,e);return e.g};_.de.prototype.D=function(a){this.g=0;_.ce(this,2,a)};_.de.prototype.G=function(a){this.g=0;_.ce(this,3,a)};
_.ce=function(a,b,c){if(a.g==0){a===c&&(b=3,c=new TypeError("F"));a.g=1;a:{var d=c,e=a.D,f=a.G;if(d instanceof _.de){ne(d,ge(e||_.ae,f||null,a));var g=!0}else if(be(d))d.then(e,f,a),g=!0;else{if(_.za(d))try{var h=d.then;if(typeof h==="function"){oe(d,h,e,f,a);g=!0;break a}}catch(l){f.call(a,l);g=!0;break a}g=!1}}g||(a.A=c,a.g=b,a.j=null,me(a),b!=3||c instanceof _.ie||pe(a,c))}};
oe=function(a,b,c,d,e){var f=!1,g=function(l){f||(f=!0,c.call(e,l))},h=function(l){f||(f=!0,d.call(e,l))};try{b.call(a,g,h)}catch(l){h(l)}};me=function(a){a.s||(a.s=!0,$d(a.F,a))};ke=function(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.l=null);return b};_.de.prototype.F=function(){for(var a;a=ke(this);)le(this,a,this.g,this.A);this.s=!1};
le=function(a,b,c,d){if(c==3&&b.h&&!b.o)for(;a&&a.o;a=a.j)a.o=!1;if(b.g)b.g.j=null,qe(b,c,d);else try{b.o?b.l.call(b.j):qe(b,c,d)}catch(e){re.call(null,e)}hb(fe,b)};qe=function(a,b,c){b==2?a.l.call(a.j,c):a.h&&a.h.call(a.j,c)};pe=function(a,b){a.o=!0;$d(function(){a.o&&re.call(null,b)})};re=_.fb;_.ie=function(a){_.aa.call(this,a)};_.B(_.ie,_.aa);_.ie.prototype.name="cancel";/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
var se=function(){this.s=[];this.l=this.g=!1;this.j=void 0;this.D=this.K=this.B=!1;this.A=0;this.h=null;this.o=0};se.prototype.cancel=function(a){if(this.g)this.j instanceof se&&this.j.cancel();else{if(this.h){var b=this.h;delete this.h;a?b.cancel(a):(b.o--,b.o<=0&&b.cancel())}this.D=!0;this.g||this.F(new _.te(this))}};se.prototype.G=function(a,b){this.B=!1;ue(this,a,b)};var ue=function(a,b,c){a.g=!0;a.j=c;a.l=!b;ve(a)},xe=function(a){if(a.g){if(!a.D)throw new we(a);a.D=!1}};
se.prototype.callback=function(a){xe(this);ue(this,!0,a)};se.prototype.F=function(a){xe(this);ue(this,!1,a)};var ze=function(a,b,c){ye(a,b,null,c)},Ae=function(a,b,c){ye(a,null,b,c)},ye=function(a,b,c,d){var e=a.g;e||(b===c?b=c=Ud(b):(b=Ud(b),c=Ud(c)));a.s.push([b,c,d]);e&&ve(a)};se.prototype.then=function(a,b,c){var d,e,f=new _.de(function(g,h){e=g;d=h});ye(this,e,function(g){g instanceof _.te?f.cancel():d(g);return Be},this);return f.then(a,b,c)};se.prototype.$goog_Thenable=!0;
var Ce=function(a,b){b instanceof se?ze(a,(0,_.A)(b.H,b)):ze(a,function(){return b})};se.prototype.H=function(a){var b=new se;ye(this,b.callback,b.F,b);a&&(b.h=this,this.o++);return b};
var De=function(a){return _.bc(a.s,function(b){return typeof b[1]==="function"})},Be={},ve=function(a){if(a.A&&a.g&&De(a)){var b=a.A,c=Ee[b];c&&(_.t.clearTimeout(c.g),delete Ee[b]);a.A=0}a.h&&(a.h.o--,delete a.h);b=a.j;for(var d=c=!1;a.s.length&&!a.B;){var e=a.s.shift(),f=e[0],g=e[1];e=e[2];if(f=a.l?g:f)try{var h=f.call(e||null,b);h===Be&&(h=void 0);h!==void 0&&(a.l=a.l&&(h==b||h instanceof Error),a.j=b=h);if(be(b)||typeof _.t.Promise==="function"&&b instanceof _.t.Promise)d=!0,a.B=!0}catch(l){b=
l,a.l=!0,De(a)||(c=!0)}}a.j=b;d&&(h=(0,_.A)(a.G,a,!0),d=(0,_.A)(a.G,a,!1),b instanceof se?(ye(b,h,d),b.K=!0):b.then(h,d));c&&(b=new Fe(b),Ee[b.g]=b,a.A=b.g)},we=function(){_.aa.call(this)};_.B(we,_.aa);we.prototype.message="Deferred has already fired";we.prototype.name="AlreadyCalledError";_.te=function(){_.aa.call(this)};_.B(_.te,_.aa);_.te.prototype.message="Deferred was canceled";_.te.prototype.name="CanceledError";
var Fe=function(a){this.g=_.t.setTimeout((0,_.A)(this.throwError,this),0);this.h=a};Fe.prototype.throwError=function(){delete Ee[this.g];throw this.h;};var Ee={};var Ge=function(a,b,c,d){this.type=a;this.status=b;this.url=d};Ge.prototype.toString=function(){return He(this)+" ("+(this.status!=void 0?this.status:"?")+")"};var He=function(a){switch(a.type){case Ge.g.vg:return"Unauthorized";case Ge.g.kg:return"Consecutive load failures";case Ge.g.TIMEOUT:return"Timed out";case Ge.g.tg:return"Out of date module id";case Ge.g.Je:return"Init error";default:return"Unknown failure type "+a.type}};Kb.Ta=Ge;Kb.Ta.g={vg:0,kg:1,TIMEOUT:2,tg:3,Je:4};var Ie=function(){Td.call(this);this.P=null;this.g={};this.l=[];this.o=[];this.K=[];this.h=[];this.A=[];this.s={};this.N={};this.j=this.F=new Qd([],"");this.oa=null;this.G=new se;this.H=!1;this.D=0;this.U=this.X=this.S=!1};_.B(Ie,Td);var Je=function(a,b){_.aa.call(this,"Error loading "+a+": "+b)};_.B(Je,_.aa);_.k=Ie.prototype;_.k.Yh=function(a){this.H=a};
_.k.Yf=function(a,b){if(!(this instanceof Ie))this.Yf(a,b);else if(typeof a==="string"){if(a.startsWith("d$")){a=a.substring(2);for(var c=[],d=0,e=a.indexOf("/"),f=0,g=!1,h=0;;){var l=g?a.substring(f):a.substring(f,e);if(l.length===0)d++,f="sy"+d.toString(36),l=[];else{var m=l.indexOf(":");if(m<0)f=l,l=[];else if(m===l.length-1)f=l.substring(0,m),l=Array(c[h-1]);else{f=l.substring(0,m);l=l.substring(m+1).split(",");m=h;for(var n=0;n<l.length;n++)m-=l[n].length===0?1:Number(l[n]),l[n]=c[m]}m=0;if(f.length===
0)m=1;else if(f.charAt(0)==="+"||f.charAt(0)==="-")m=Number(f);m!==0&&(d+=m,f="sy"+d.toString(36))}c.push(f);Ke(this,f,l);if(g)break;f=e+1;e=a.indexOf("/",f);e===-1&&(g=!0);h++}this.P=c}else{a=a.split("/");c=[];for(d=0;d<a.length;d++){h=a[d].split(":");e=h[0];g=[];if(h[1])for(g=h[1].split(","),h=0;h<g.length;h++)g[h]=c[parseInt(g[h],36)];c.push(e);Ke(this,e,g)}this.P=c}b&&b.length?(ya(this.l,b),this.oa=b[b.length-1]):this.G.g||this.G.callback();Object.freeze(this.P);Le(this)}};
_.k.Uh=function(a,b){if(this.s[a]){delete this.s[a][b];for(var c in this.s[a])return;delete this.s[a]}};_.k.Zf=function(a){Ie.O.Zf.call(this,a);Le(this)};_.k.isActive=function(){return this.l.length>0};_.k.vh=function(){return this.A.length>0};
var Ne=function(a){var b=a.S,c=a.isActive();c!=b&&(Me(a,c?"active":"idle"),a.S=c);b=a.vh();b!=a.X&&(Me(a,b?"userActive":"userIdle"),a.X=b)},Ke=function(a,b,c){a.g[b]?(a=a.g[b].h,a!=c&&a.splice.apply(a,[0,a.length].concat(_.zb(c)))):a.g[b]=new Qd(c,b)},Qe=function(a,b,c){var d=[];Ba(b,d);b=[];for(var e={},f=0;f<d.length;f++){var g=d[f],h=a.g[g];if(!h)throw Error("G`"+g);var l=new se;e[g]=l;h.g?l.callback(a.Ca):(Oe(a,g,h,!!c,l),Pe(a,g)||b.push(g))}b.length>0&&(a.l.length===0?a.M(b):(a.h.push(b),Ne(a)));
return e},Oe=function(a,b,c,d,e){c.o.push(new Pd(e.callback,e));Rd(c,function(f){e.F(new Je(b,f))});Pe(a,b)?d&&(_.ua(a.A,b)||a.A.push(b),Ne(a)):d&&(_.ua(a.A,b)||a.A.push(b))};
Ie.prototype.M=function(a,b,c){var d=this;b||(this.D=0);var e=Re(this,a);this.l=e;this.o=this.H?a:_.xa(e);Ne(this);if(e.length!==0){this.K.push.apply(this.K,e);if(Object.keys(this.s).length>0&&!this.B.H)throw Error("H");a=(0,_.A)(this.B.G,this.B,_.xa(e),this.g,{nj:this.s,qj:!!c,Jf:function(f,g){var h=d.o;f=f!=null?f:void 0;d.D++;var l=_.xa(e);d.o=h;e.forEach(_.Rb(_.wa,d.K),d);f==401?(Se(d,new Kb.Ta(Kb.Ta.g.vg,f)),d.h.length=0):f==410?(Te(d,new Kb.Ta(Kb.Ta.g.tg,f)),Ue(d)):d.D>=3?(Te(d,new Kb.Ta(Kb.Ta.g.kg,
f,l,g)),Ue(d)):d.M(d.o,!0,f==8001||!1)},Uk:(0,_.A)(this.ga,this)});(b=Math.pow(this.D,2)*5E3)?_.t.setTimeout(a,b):a()}};
var Re=function(a,b){b=b.filter(function(e){return a.g[e].g?(_.t.setTimeout(function(){return Error("I`"+e)},0),!1):!0});for(var c=[],d=0;d<b.length;d++)c=c.concat(Ve(a,b[d]));Ba(c);return!a.H&&c.length>1?(b=c.shift(),a.h=c.map(function(e){return[e]}).concat(a.h),[b]):c},Ve=function(a,b){var c=Ha(a.K),d=[];c[b]||d.push(b);b=[b];for(var e=0;e<b.length;e++)for(var f=a.g[b[e]].h,g=f.length-1;g>=0;g--){var h=f[g];a.g[h].g||c[h]||(d.push(h),b.push(h))}d.reverse();Ba(d);return d},Le=function(a){a.j==a.F&&
(a.j=null,a.F.onLoad((0,_.A)(a.Ug,a))&&Se(a,new Kb.Ta(Kb.Ta.g.Je)),Ne(a))},la=function(a){if(a.j){var b=a.j.Za(),c=[];if(a.s[b]){for(var d=_.y(Object.keys(a.s[b])),e=d.next();!e.done;e=d.next()){e=e.value;var f=a.g[e];f&&!f.g&&(a.Uh(b,e),c.push(e))}Qe(a,c)}a.fb()||(a.g[b].onLoad((0,_.A)(a.Ug,a))&&Se(a,new Kb.Ta(Kb.Ta.g.Je)),_.wa(a.A,b),_.wa(a.l,b),a.l.length===0&&Ue(a),a.oa&&b==a.oa&&(a.G.g||a.G.callback()),Ne(a),a.j=null)}},Pe=function(a,b){if(_.ua(a.l,b))return!0;for(var c=0;c<a.h.length;c++)if(_.ua(a.h[c],
b))return!0;return!1};Ie.prototype.load=function(a,b){return Qe(this,[a],b)[a]};var ja=function(a){var b=_.ca;b.j&&b.j.Za()==="synthetic_module_overhead"&&(la(b),delete b.g.synthetic_module_overhead);b.g[a]&&We(b,b.g[a].h||[],function(c){c.g=new Od;_.wa(b.l,c.Za())},function(c){return!c.g});b.j=b.g[a]};Ie.prototype.Sh=function(a){this.j||(this.g.synthetic_module_overhead=new Qd([],"synthetic_module_overhead"),this.j=this.g.synthetic_module_overhead);this.j.j.push(new Pd(a))};
Ie.prototype.ga=function(){Te(this,new Kb.Ta(Kb.Ta.g.TIMEOUT));Ue(this)};
var Te=function(a,b){a.o.length>1?a.h=a.o.map(function(c){return[c]}).concat(a.h):Se(a,b)},Se=function(a,b){var c=a.o;a.l.length=0;for(var d=[],e=0;e<a.h.length;e++){var f=a.h[e].filter(function(l){var m=Ve(this,l);return _.bc(c,function(n){return _.ua(m,n)})},a);ya(d,f)}for(e=0;e<c.length;e++)_.va(d,c[e]);for(e=0;e<d.length;e++){for(f=0;f<a.h.length;f++)_.wa(a.h[f],d[e]);_.wa(a.A,d[e])}if(e=a.N.error)for(f=0;f<e.length;f++)for(var g=e[f],h=0;h<d.length;h++)g("error",d[h],b);for(d=0;d<c.length;d++)a.g[c[d]]&&
a.g[c[d]].Jf(b);a.o.length=0;Ne(a)},Ue=function(a){for(;a.h.length;){var b=a.h.shift().filter(function(c){return!this.g[c].g},a);if(b.length>0){a.M(b);return}}Ne(a)},Me=function(a,b){a=a.N[b];for(var c=0;a&&c<a.length;c++)a[c](b)},We=function(a,b,c,d,e){d=d===void 0?function(){return!0}:d;e=e===void 0?{}:e;b=_.y(b);for(var f=b.next();!f.done;f=b.next()){f=f.value;var g=a.g[f];!e[f]&&d(g)&&(e[f]=!0,We(a,g.h||[],c,d,e),c(g))}};
Ie.prototype.dispose=function(){sa(Da(this.g),this.F);this.g={};this.l=[];this.o=[];this.A=[];this.h=[];this.N={};this.U=!0};Ie.prototype.fb=function(){return this.U};_.fa=function(){return new Ie};var Xe=function(a,b){this.g=a[_.t.Symbol.iterator]();this.h=b};Xe.prototype[Symbol.iterator]=function(){return this};Xe.prototype.next=function(){var a=this.g.next();return{value:a.done?void 0:this.h.call(void 0,a.value),done:a.done}};var Ye=function(a,b){return new Xe(a,b)};_.Ze=function(){};_.Ze.prototype.next=function(){return _.$e};_.$e={done:!0,value:void 0};_.Ze.prototype.Fb=function(){return this};var df=function(a){if(a instanceof af||a instanceof bf||a instanceof cf)return a;if(typeof a.next=="function")return new af(function(){return a});if(typeof a[Symbol.iterator]=="function")return new af(function(){return a[Symbol.iterator]()});if(typeof a.Fb=="function")return new af(function(){return a.Fb()});throw Error("J");},af=function(a){this.g=a};af.prototype.Fb=function(){return new bf(this.g())};af.prototype[Symbol.iterator]=function(){return new cf(this.g())};af.prototype.h=function(){return new cf(this.g())};
var bf=function(a){this.g=a};_.x(bf,_.Ze);bf.prototype.next=function(){return this.g.next()};bf.prototype[Symbol.iterator]=function(){return new cf(this.g)};bf.prototype.h=function(){return new cf(this.g)};var cf=function(a){af.call(this,function(){return a});this.j=a};_.x(cf,af);cf.prototype.next=function(){return this.j.next()};_.ef=function(a,b){this.h={};this.g=[];this.j=this.size=0;var c=arguments.length;if(c>1){if(c%2)throw Error("w");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof _.ef)for(c=a.Zb(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};_.k=_.ef.prototype;_.k.lb=function(){return this.size};_.k.La=function(){ff(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};_.k.Zb=function(){ff(this);return this.g.concat()};
_.k.has=function(a){return gf(this.h,a)};_.k.Qc=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if(gf(this.h,c)&&this.h[c]==a)return!0}return!1};_.k.equals=function(a,b){if(this===a)return!0;if(this.size!=a.lb())return!1;b=b||hf;ff(this);for(var c,d=0;c=this.g[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};var hf=function(a,b){return a===b};_.ef.prototype.clear=function(){this.h={};this.j=this.size=this.g.length=0};_.ef.prototype.remove=function(a){return this.delete(a)};
_.ef.prototype.delete=function(a){return gf(this.h,a)?(delete this.h[a],--this.size,this.j++,this.g.length>2*this.size&&ff(this),!0):!1};var ff=function(a){if(a.size!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];gf(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.size!=a.g.length){b={};for(d=c=0;c<a.g.length;){var e=a.g[c];gf(b,e)||(a.g[d++]=e,b[e]=1);c++}a.g.length=d}};_.k=_.ef.prototype;_.k.get=function(a,b){return gf(this.h,a)?this.h[a]:b};
_.k.set=function(a,b){gf(this.h,a)||(this.size+=1,this.g.push(a),this.j++);this.h[a]=b};_.k.forEach=function(a,b){for(var c=this.Zb(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.k.keys=function(){return df(this.Fb(!0)).h()};_.k.values=function(){return df(this.Fb(!1)).h()};_.k.entries=function(){var a=this;return Ye(this.keys(),function(b){return[b,a.get(b)]})};
_.k.Fb=function(a){ff(this);var b=0,c=this.j,d=this,e=new _.Ze;e.next=function(){if(c!=d.j)throw Error("K");if(b>=d.g.length)return _.$e;var f=d.g[b++];return{value:a?f:d.h[f],done:!1}};return e};var gf=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var jf,mf;jf=function(a){if(a.lb&&typeof a.lb=="function")a=a.lb();else if(_.qa(a)||typeof a==="string")a=a.length;else{var b=0,c;for(c in a)b++;a=b}return a};_.kf=function(a){if(a.La&&typeof a.La=="function")return a.La();if(typeof Map!=="undefined"&&a instanceof Map||typeof Set!=="undefined"&&a instanceof Set)return Array.from(a.values());if(typeof a==="string")return a.split("");if(_.qa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Da(a)};
_.lf=function(a){if(a.Zb&&typeof a.Zb=="function")return a.Zb();if(!a.La||typeof a.La!="function"){if(typeof Map!=="undefined"&&a instanceof Map)return Array.from(a.keys());if(!(typeof Set!=="undefined"&&a instanceof Set)){if(_.qa(a)||typeof a==="string"){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}return _.Ea(a)}}};
mf=function(a,b){if(typeof a.every=="function")return a.every(b,void 0);if(_.qa(a)||typeof a==="string")return Array.prototype.every.call(a,b,void 0);for(var c=_.lf(a),d=_.kf(a),e=d.length,f=0;f<e;f++)if(!b.call(void 0,d[f],c&&c[f],a))return!1;return!0};var of;_.nf=function(a){this.g=new _.ef;this.size=0;if(a){a=_.kf(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c]);this.size=this.g.size}};of=function(a){var b=typeof a;return b=="object"&&a||b=="function"?"o"+_.Aa(a):b.charAt(0)+a};_.k=_.nf.prototype;_.k.lb=function(){return this.g.size};_.k.add=function(a){this.g.set(of(a),a);this.size=this.g.size};_.k.delete=function(a){a=this.g.remove(of(a));this.size=this.g.size;return a};_.k.remove=function(a){return this.delete(a)};
_.k.clear=function(){this.g.clear();this.size=0};_.k.has=function(a){var b=this.g;a=of(a);return b.has(a)};_.k.contains=function(a){var b=this.g;a=of(a);return b.has(a)};_.k.La=function(){return this.g.La()};_.k.values=function(){return this.g.values()};_.k.equals=function(a){return this.lb()==jf(a)&&pf(this,a)};
var pf=function(a,b){var c=jf(b);if(a.lb()>c)return!1;!(b instanceof _.nf)&&c>5&&(b=new _.nf(b));return mf(a,function(d){var e=b;if(e.contains&&typeof e.contains=="function")d=e.contains(d);else if(e.Qc&&typeof e.Qc=="function")d=e.Qc(d);else if(_.qa(e)||typeof e==="string")d=_.ua(e,d);else a:{for(var f in e)if(e[f]==d){d=!0;break a}d=!1}return d})};_.nf.prototype.Fb=function(){return this.g.Fb(!1)};_.nf.prototype[Symbol.iterator]=function(){return this.values()};var qf=[],rf=function(a){function b(d){d&&ac(d,function(e,f){e[f.id]=!0;return e},c.al)}var c={al:{},index:qf.length,wo:a};b(a.g);b(a.j);qf.push(c);a.g&&_.Yb(a.g,function(d){var e=d.id;e instanceof D&&d.module&&(e.g=d.module)})};new D("zZa4xc");new D("WwG67d");new D("pVbxBc");new D("yu4DA");new D("Bgf0ib");var sf=new D("MpJwZc","MpJwZc");_.tf=new D("UUJqVe","UUJqVe");new D("ABma3e");_.uf=new D("GHAeAc","GHAeAc");_.vf=new D("Wt6vjf","Wt6vjf");new D("AzG0ke");new D("WSziFf");_.wf=new D("byfTOb","byfTOb");new D("d0RAGb");new D("TuDsZ");new D("o1bZcd");new D("b8xKu");_.xf=new D("LEikZe","LEikZe");_.yf=new D("lsjVmc","lsjVmc");new D("klpyYe");new D("OPbIxb");new D("pg9hFd");new D("IaqD3e");new D("Xpw1of");new D("v5BQle");new D("tdUkaf");new D("UBSgGf");new D("amY3Td");new D("gSshPb");new D("J5K1Ad");new D("tLnxq");rf({g:[{id:_.Wb,vb:Nd,multiple:!0}]});var Cf;_.zf=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");_.Af=function(a){return a?decodeURI(a):a};_.Bf=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(d>=0){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?_.nc(e):"")}}};
Cf=function(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)Cf(a,String(b[d]),c);else b!=null&&c.push(a+(b===""?"":"="+_.mc(b)))};var Df={};var Ef=new kd,Ff=function(a,b,c){_.ld.call(this,a,b);this.node=b;this.kind=c};_.x(Ff,_.ld);_.Gf=RegExp("^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)","i");_.Hf=function(a,b){b||_.Xc();this.j=a||null};_.Hf.prototype.fa=function(a,b){a=a(b||{},this.j?this.j.g():{});this.h(null,"function"==typeof _.If&&a instanceof _.If?a.Vb:null);return String(a)};_.Hf.prototype.h=function(){};var Jf=function(a){this.h=a;this.j=this.h.g(_.tf)};Jf.prototype.g=function(){this.h.fb()||(this.j=this.h.g(_.tf));return this.j?this.j.l():{}};var Kf=function(a){var b=new Jf(a);_.Hf.call(this,b,a.get(_.Wb).h);this.l=new _.I;this.o=b};_.x(Kf,_.Hf);Kf.prototype.g=function(){return this.o.g()};Kf.prototype.h=function(a,b){_.Hf.prototype.h.call(this,a,b);this.l.dispatchEvent(new Ff(Ef,a,b))};_.oa(sf,Kf);rf({g:[{id:sf,vb:Kf,multiple:!0}]});var Lf=function(a,b){this.defaultValue=a;this.type=b;this.value=a};Lf.prototype.get=function(){return this.value};Lf.prototype.set=function(a){this.value=a};var Mf=function(a){Lf.call(this,a,"b")};_.x(Mf,Lf);Mf.prototype.get=function(){return this.value};var Nf=function(a){this.nd=a};Nf.prototype.toString=function(){return this.nd.join(".")};var Of=function(a){this.nd=a};Of.prototype.toString=function(){return this.nd.join(".")};var Pf=function(a){var b=a.split(".");b=b.length!==4&&b.length!==3||b[0].indexOf("=")!==-1?null:new Of(b);if(b===null)throw new TypeError("R`"+a);return b};var Qf=function(){this.g={};this.h="";this.j={};this.l=".wasm"};Qf.prototype.toString=function(){if(this.h.endsWith("_/wa/"))var a=this.h+Rf(this,"wk")+this.l;else if(this.h.endsWith("_/r/"))a=this.h+Rf(this,"sc");else{a=this.h+Sf(this);var b=this.j;var c=[],d;for(d in b)Cf(d,b[d],c);b=c.join("&");c="";b!=""&&(c="?"+b);a+=c}return a};
var Tf=function(a){a=Rf(a,"md");return!!a&&a!=="0"},Sf=function(a){var b=[],c=(0,_.A)(function(d){this.g[d]!==void 0&&b.push(d+"="+this.g[d])},a);Tf(a)?(c("md"),c("k"),c("ck"),c("am"),c("rs"),c("gssmodulesetproto"),c("tpc")):(c("sdch"),c("k"),c("ck"),c("am"),c("rt"),"d"in a.g||Uf(a,"d","0"),c("d"),c("exm"),c("excm"),(a.g.excm||a.g.exm)&&b.push("ed=1"),c("im"),c("dg"),c("sm"),Rf(a,"br")=="1"&&c("br"),c("br-d"),Rf(a,"rb")=="1"&&c("rb"),Rf(a,"zs")!=="0"&&c("zs"),Vf(a)!==""&&c("wt"),c("gssmodulesetproto"),
c("ujg"),c("sp"),c("rs"),c("cb"),c("ee"),c("tpc"),c("sl"),c("m"));return b.join("/")},Rf=function(a,b){return a.g[b]?a.g[b]:null},Uf=function(a,b,c){c?a.g[b]=c:delete a.g[b]},Vf=function(a){switch(Rf(a,"wt")){case "0":return"0";case "1":return"1";case "2":return"2";default:return""}},ag=function(a){var b=b===void 0?!0:b;var c=Wf(a),d=new Qf,e=c.match(_.zf)[5];_.ec(Xf,function(h){var l=e.match("/"+h+"=([^/]+)");l&&Uf(d,h,l[1])});var f="";f=a.indexOf("_/ss/")!=-1?"_/ss/":a.indexOf("_/wa/")!=-1?"_/wa/":
a.indexOf("_/r/")!=-1?"_/r/":"_/js/";d.h=a.substr(0,a.indexOf(f)+f.length);if(d.h.endsWith("_/wa/")){b=Yf(a);var g=!0;Object.values(Zf).forEach(function(h){a.endsWith(h)&&(d.l=h,g=!1)});g&&(c=a.split("/"),d.l="/"+c[c.length-1]);Uf(d,"wk",b.toString());return d}if(d.h.endsWith("_/r/"))return Uf(d,"sc",$f(a).toString()),d;if(!b)return d;(b=c.match(_.zf)[6]||null)&&_.Bf(b,function(h,l){d.j[h]=l});return d},Yf=function(a){var b=null,c=a.lastIndexOf("_/wa/")+5,d=a.indexOf("/",c);d!==-1?b=a.slice(c,d):
Object.values(Zf).forEach(function(e){a.endsWith(e)&&(b=a.slice(c,a.lastIndexOf(e)))});if(b===null)return null;try{return Pf(b)}catch(e){return null}},$f=function(a){a=a.slice(a.lastIndexOf("_/r/")+4);if(a===null)return null;try{var b=a.split(".");var c=b.length!==2?null:new Nf(b);if(c===null)throw new TypeError("Q`"+a);return c}catch(d){return null}},Wf=function(a){return a.startsWith("https://uberproxy-pen-redirect.corp.google.com/uberproxy/pen?url=")?a.substr(65):a},Xf={zm:"k",Ll:"ck",gn:"wk",
nm:"m",Vl:"exm",Tl:"excm",Cl:"am",lm:"mm",ym:"rt",fm:"d",Ul:"ed",Km:"sv",Ml:"deob",Jl:"cb",Gm:"rs",Am:"sdch",gm:"im",Nl:"dg",Rl:"br",Ql:"br-d",Sl:"rb",ln:"zs",kn:"wt",Wl:"ee",Jm:"sm",mm:"md",cm:"gssmodulesetproto",cn:"ujg",an:"sp",Tm:"tpc",em:"ichc",Nm:"sc",Fm:"sl"},Zf={fn:".wasm",Im:".map",Qm:".symbols",hm:".loader.js",im:".loader.sourcemap",hn:".worker.js",jn:".worker.sourcemap"};_.bg=function(a){_.E.call(this);this.h=a;this.g={}};_.B(_.bg,_.E);var cg=[];_.bg.prototype.J=function(a,b,c,d){return dg(this,a,b,c,d)};var dg=function(a,b,c,d,e,f){Array.isArray(c)||(c&&(cg[0]=c.toString()),c=cg);for(var g=0;g<c.length;g++){var h=_.G(b,c[g],d||a.handleEvent,e||!1,f||a.h||a);if(!h)break;a.g[h.key]=h}return a};_.bg.prototype.Mb=function(a,b,c,d){return eg(this,a,b,c,d)};
var eg=function(a,b,c,d,e,f){if(Array.isArray(c))for(var g=0;g<c.length;g++)eg(a,b,c[g],d,e,f);else{b=_.Ad(b,c,d||a.handleEvent,e,f||a.h||a);if(!b)return a;a.g[b.key]=b}return a};_.bg.prototype.gb=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.gb(a,b[f],c,d,e);else c=c||this.handleEvent,d=_.za(d)?!!d.capture:!!d,e=e||this.h||this,c=Bd(c),d=!!d,b=_.pd(a)?a.Xc(b,c,d,e):a?(a=_.Dd(a))?a.Xc(b,c,d,e):null:null,b&&(_.Id(b),delete this.g[b.key]);return this};
_.fg=function(a){_.ec(a.g,function(b,c){this.g.hasOwnProperty(c)&&_.Id(b)},a);a.g={}};_.bg.prototype.I=function(){_.bg.O.I.call(this);_.fg(this)};_.bg.prototype.handleEvent=function(){throw Error("S");};var gg=function(){};var hg,ig=function(){};_.B(ig,gg);ig.prototype.g=function(){return new XMLHttpRequest};hg=new ig;var jg=function(){};_.B(jg,gg);jg.prototype.g=function(){var a=new XMLHttpRequest;if("withCredentials"in a)return a;if(typeof XDomainRequest!="undefined")return new kg;throw Error("T");};var kg=function(){this.g=new XDomainRequest;this.readyState=0;this.onreadystatechange=null;this.responseType=this.responseText="";this.status=-1;this.statusText="";this.g.onload=(0,_.A)(this.ni,this);this.g.onerror=(0,_.A)(this.mg,this);this.g.onprogress=(0,_.A)(this.ck,this);this.g.ontimeout=(0,_.A)(this.gk,this)};
_.k=kg.prototype;_.k.open=function(a,b,c){if(c!=null&&!c)throw Error("U");this.g.open(a,b)};_.k.send=function(a){if(a)if(typeof a=="string")this.g.send(a);else throw Error("V");else this.g.send()};_.k.abort=function(){this.g.abort()};_.k.setRequestHeader=function(){};_.k.getResponseHeader=function(a){return a.toLowerCase()=="content-type"?this.g.contentType:""};_.k.ni=function(){this.status=200;this.responseText=this.g.responseText;lg(this,4)};
_.k.mg=function(){this.status=500;this.responseText="";lg(this,4)};_.k.gk=function(){this.mg()};_.k.ck=function(){this.status=200;lg(this,1)};var lg=function(a,b){a.readyState=b;if(a.onreadystatechange)a.onreadystatechange()};kg.prototype.getAllResponseHeaders=function(){return"content-type: "+this.g.contentType};var ng,og;_.mg=function(a){_.I.call(this);this.headers=new Map;this.N=a||null;this.h=!1;this.g=null;this.s="";this.o=0;this.j=this.G=this.A=this.D=!1;this.B=0;this.l=null;this.K="";this.F=!1};_.B(_.mg,_.I);ng=/^https?$/i;og=["POST","PUT"];_.pg=[];_.mg.prototype.M=function(){this.dispose();_.wa(_.pg,this)};
_.mg.prototype.send=function(a,b,c,d){if(this.g)throw Error("X`"+this.s+"`"+a);b=b?b.toUpperCase():"GET";this.s=a;this.o=0;this.D=!1;this.h=!0;this.g=this.N?this.N.g():hg.g();this.g.onreadystatechange=Ud((0,_.A)(this.H,this));try{this.G=!0,this.g.open(b,String(a),!0),this.G=!1}catch(g){qg(this);return}a=c||"";c=new Map(this.headers);if(d)if(Object.getPrototypeOf(d)===Object.prototype)for(var e in d)c.set(e,d[e]);else if(typeof d.keys==="function"&&typeof d.get==="function"){e=_.y(d.keys());for(var f=
e.next();!f.done;f=e.next())f=f.value,c.set(f,d.get(f))}else throw Error("Y`"+String(d));d=Array.from(c.keys()).find(function(g){return"content-type"==g.toLowerCase()});e=_.t.FormData&&a instanceof _.t.FormData;!_.ua(og,b)||d||e||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=_.y(c);for(d=b.next();!d.done;d=b.next())c=_.y(d.value),d=c.next().value,c=c.next().value,this.g.setRequestHeader(d,c);this.K&&(this.g.responseType=this.K);"withCredentials"in this.g&&this.g.withCredentials!==
this.F&&(this.g.withCredentials=this.F);try{this.l&&(clearTimeout(this.l),this.l=null),this.B>0&&(this.l=setTimeout(this.U.bind(this),this.B)),this.A=!0,this.g.send(a),this.A=!1}catch(g){qg(this)}};_.mg.prototype.U=function(){typeof Gb!="undefined"&&this.g&&(this.o=8,this.dispatchEvent("timeout"),this.abort(8))};var qg=function(a){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);a.o=5;rg(a);sg(a)},rg=function(a){a.D||(a.D=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};
_.mg.prototype.abort=function(a){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,this.o=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),sg(this))};_.mg.prototype.I=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),sg(this,!0));_.mg.O.I.call(this)};_.mg.prototype.H=function(){this.fb()||(this.G||this.A||this.j?tg(this):this.P())};_.mg.prototype.P=function(){tg(this)};
var tg=function(a){if(a.h&&typeof Gb!="undefined")if(a.A&&(a.g?a.g.readyState:0)==4)setTimeout(a.H.bind(a),0);else if(a.dispatchEvent("readystatechange"),(a.g?a.g.readyState:0)==4){a.h=!1;try{_.ug(a)?(a.dispatchEvent("complete"),a.dispatchEvent("success")):(a.o=6,rg(a))}finally{sg(a)}}},sg=function(a,b){if(a.g){a.l&&(clearTimeout(a.l),a.l=null);var c=a.g;a.g=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=null}catch(d){}}};_.mg.prototype.isActive=function(){return!!this.g};
_.ug=function(a){var b=_.vg(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=b===0)a=String(a.s).match(_.zf)[1]||null,!a&&_.t.self&&_.t.self.location&&(a=_.t.self.location.protocol.slice(0,-1)),b=!ng.test(a?a.toLowerCase():"");c=b}return c};_.vg=function(a){try{return(a.g?a.g.readyState:0)>2?a.g.status:-1}catch(b){return-1}};_.wg=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}};var yg=function(a){_.E.call(this);this.D=a;this.A=ag(a);this.l=this.o=null;this.H=!0;this.h=new _.bg(this);this.K=[];this.s=new Set;this.g=[];this.N=new xg;this.j=[];this.B=!1;a=(0,_.A)(this.F,this);Df.version=a};_.x(yg,_.E);var zg=function(a,b){a.g.length&&Ce(b,a.g[a.g.length-1]);a.g.push(b);ze(b,function(){_.wa(this.g,b)},a)};yg.prototype.G=function(a,b,c){var d=c===void 0?{}:c;var e=d.nj;c=d.qj;var f=d.Jf;d=d.Uk;a=Ag(this,a,b,e,c);Bg(this,a,f,d,c)};
var Ag=function(a,b,c,d,e){d=d===void 0?{}:d;var f=[];Cg(a,b,c,d,e===void 0?!1:e,function(g){f.push(g.Za())});return f},Cg=function(a,b,c,d,e,f,g){g=g===void 0?{}:g;b=_.y(b);for(var h=b.next();!h.done;h=b.next()){var l=h.value;h=c[l];!e&&(a.s.has(l)||h.g)||g[l]||(g[l]=!0,l=d[l]?Object.keys(d[l]):[],Cg(a,h.h.concat(l),c,d,e,f,g),f(h))}},Bg=function(a,b,c,d,e){e=e===void 0?!1:e;var f=[],g=new se;b=[b];for(var h=function(p,q){for(var r=[],u=0,C=Math.floor(p.length/q)+1,H=0;H<q;H++){var F=(H+1)*C;r.push(p.slice(u,
F));u=F}return r},l=b.shift();l;){var m=Dg(a,l,!!e,!0);if(m.length<=2E3){if(l=Eg(a,l,e))f.push(l),Ce(g,l.g)}else b=h(l,Math.ceil(m.length/2E3)).concat(b);l=b.shift()}var n=new se;zg(a,n);ze(n,function(){return Fg(a,f,c,d)});Ae(n,function(){var p=new Gg;p.j=!0;p.h=-1;Fg(this,[p],c,d)},a);ze(g,function(){return n.callback()});g.callback()},Eg=function(a,b,c){var d=Dg(a,b,!(c===void 0||!c));a.K.push(d);b=_.y(b);for(c=b.next();!c.done;c=b.next())a.s.add(c.value);if(a.B)a=_.cd(document,"SCRIPT"),_.Ua(a,
_.mb(d)),a.type="text/javascript",a.async=!1,document.body.appendChild(a);else{var e=new Gg,f=new _.mg(a.j.length>0?new jg:void 0);a.h.J(f,"success",(0,_.A)(e.B,e,f));a.h.J(f,"error",(0,_.A)(e.A,e,f));a.h.J(f,"timeout",(0,_.A)(e.s,e));dg(a.h,f,"ready",f.dispose,!1,f);f.B=3E4;Hg(a.N,function(){f.send(d);return e.g});return e}return null},Fg=function(a,b,c,d){for(var e=!1,f,g=!1,h=0;h<b.length;h++){var l=b[h];if(!f&&l.j){e=!0;f=l.h;break}else l.l&&(g=!0)}h=_.xa(a.g);(e||g)&&f!=-1&&(a.g.length=0);if(e)c&&
c(f);else if(g)d&&d();else for(a=0;a<b.length;a++)d=b[a],Ig(d.o,d.Pa)||c&&c(8001);(e||g)&&f!=-1&&_.Yb(h,function(m){m.cancel()})};yg.prototype.I=function(){this.h.dispose();delete Df.version;_.E.prototype.I.call(this)};yg.prototype.F=function(){return Rf(this.A,"k")};
var Dg=function(a,b,c,d){d=d===void 0?!1:d;var e=_.Af(a.D.match(_.zf)[3]||null);if(a.j.length>0&&!_.ua(a.j,e)&&e!=null&&window.location.hostname!=e)throw Error("aa`"+e);e=ag(a.A.toString());delete e.g.m;delete e.g.exm;delete e.g.ed;Uf(e,"m",b.join(","));a.o&&(Uf(e,"ck",a.o),a.l&&Uf(e,"rs",a.l));Uf(e,"d","0");c&&(a=_.oc(),e.j.zx=a);a=e.toString();if(d&&a.lastIndexOf("/",0)==0){e=document.location.href.match(_.zf);d=e[1];b=e[2];c=e[3];e=e[4];var f="";d&&(f+=d+":");c&&(f+="//",b&&(f+=b+"@"),f+=c,e&&
(f+=":"+e));a=f+a}return a},Ig=function(a,b){var c="";if(a.length>1&&a.charAt(a.length-1)==="\n"){var d=a.lastIndexOf("\n",a.length-2);d>=0&&(c=a.substring(d+1,a.length-1))}d=c.length-11;if(d>=0&&c.indexOf("Google Inc.",d)==d||c.lastIndexOf("//# sourceMappingURL=",0)==0)try{c=window;a=a+"\r\n//# sourceURL="+b;a=_.lb(a);var e=_.Sa(a);var f=_.Ta(e);c.eval(f)===f&&c.eval(f.toString())}catch(g){return!1}else return!1;return!0},Jg=function(a){var b=_.Af(a.match(_.zf)[5]||null)||"",c=_.Af(Wf(b).match(_.zf)[5]||
null);return(c===null?0:RegExp("/_/wa/","g").test(c)?Yf(b):RegExp("/_/r/","g").test(c)?$f(b):RegExp("(/_/js/)|(/_/ss/)","g").test(c)&&/\/k=/.test(c))?a:null},Gg=function(){this.g=new se;this.Pa=this.o="";this.j=!1;this.h=0;this.l=!1};Gg.prototype.B=function(a){this.o=_.wg(a);this.Pa=String(a.s);this.g.callback()};Gg.prototype.A=function(a){this.j=!0;this.h=_.vg(a);this.g.callback()};Gg.prototype.s=function(){this.l=!0;this.g.callback()};
var xg=function(){this.g=0;this.h=[]},Hg=function(a,b){a.h.push(b);Kg(a)},Kg=function(a){for(;a.g<5&&a.h.length;)Lg(a,a.h.shift())},Lg=function(a,b){a.g++;ze(b(),function(){this.g--;Kg(this)},a)};var Mg=new Mf(!1),Ng=document.location.href;
rf({h:{dml:Mg},initialize:function(a){var b=Mg.get(),c="",d="";window&&window._F_cssRowKey&&(c=window._F_cssRowKey,window._F_combinedSignature&&(d=window._F_combinedSignature));if(c&&typeof window._F_installCss!=="function")throw Error("Z");var e,f=_.t._F_jsUrl;f&&(e=Jg(f));!e&&(f=document.getElementById("base-js"))&&(e=f.src?f.src:f.getAttribute("href"),e=Jg(e));e||(e=Jg(Ng));e||(e=document.getElementsByTagName("script"),e=Jg(e[e.length-1].src));if(!e)throw Error("$");e=new yg(e);c&&(e.o=c);d&&(e.l=
d);e.B=b;b=_.ia();b.B=e;b.Yh(!0);b=_.ia();b.Zf(a);a.A(b)}});
_._ModuleManager_initialize=function(a,b){if(!_.ca){if(!_.fa)return;_.ha()}_.ca.Yf(a,b)};
_._ModuleManager_initialize('b/n73qwf/sy0/sy1:2/sy2/sy3/rJmJrc:3,4,5/sy4:3/byfTOb:7/sy5/sy6:9/sy7:a/sy8/sy9:9/LEikZe:4,5,7,b,c,d/UUJqVe/MpJwZc/GHAeAc/sya/Wt6vjf:4,a,i/lsjVmc:b,c/syb/el_conf:l/el_main_css/syd:b,i/sye:9/syf/el_main:2,d,l,n,o,p,q/corsproxy/website_error/syg/navigationui:a,q,u/phishing_protection:o,u/_stam:p',['syb','el_conf']);
}catch(e){_._DumpException(e)}
try{
_.N={};MSG_TRANSLATE="Translate";_.N[0]=MSG_TRANSLATE;MSG_CANCEL="Cancel";_.N[1]=MSG_CANCEL;MSG_CLOSE="Close";_.N[2]=MSG_CLOSE;MSGFUNC_PAGE_TRANSLATED_TO=function(a){return"Google has translated this page automatically to: "+a};_.N[3]=MSGFUNC_PAGE_TRANSLATED_TO;MSGFUNC_TRANSLATED_TO=function(a){return"Translated into: "+a};_.N[4]=MSGFUNC_TRANSLATED_TO;MSG_GENERAL_ERROR="Error: The server could not complete your request. Try again later.";_.N[5]=MSG_GENERAL_ERROR;MSG_LEARN_MORE="Learn more";
_.N[6]=MSG_LEARN_MORE;MSGFUNC_POWERED_BY=function(a){return"Powered by "+a};_.N[7]=MSGFUNC_POWERED_BY;MSG_TRANSLATE_PRODUCT_NAME="Translate";_.N[8]=MSG_TRANSLATE_PRODUCT_NAME;MSG_TRANSLATION_IN_PROGRESS="Translation in progress";_.N[9]=MSG_TRANSLATION_IN_PROGRESS;MSGFUNC_TRANSLATE_PAGE_TO=function(a){return"Translate this page to: "+a+" using Google Translate?"};_.N[10]=MSGFUNC_TRANSLATE_PAGE_TO;MSGFUNC_VIEW_PAGE_IN=function(a){return"View this page in: "+a};_.N[11]=MSGFUNC_VIEW_PAGE_IN;
MSG_RESTORE="Show original";_.N[12]=MSG_RESTORE;MSG_SSL_INFO_LOCAL_FILE="The content of this local file will be sent to Google for translation using a secure connection.";_.N[13]=MSG_SSL_INFO_LOCAL_FILE;MSG_SSL_INFO_SECURE_PAGE="The content of this secure page will be sent to Google for translation, using a secure connection.";_.N[14]=MSG_SSL_INFO_SECURE_PAGE;MSG_SSL_INFO_INTRANET_PAGE="The content of this intranet page will be sent to Google for translation, using a secure connection.";_.N[15]=MSG_SSL_INFO_INTRANET_PAGE;
MSG_SELECT_LANGUAGE="Select Language";_.N[16]=MSG_SELECT_LANGUAGE;MSGFUNC_TURN_OFF_TRANSLATION=function(a){return"Turn off "+a+" translation"};_.N[17]=MSGFUNC_TURN_OFF_TRANSLATION;MSGFUNC_TURN_OFF_FOR=function(a){return"Turn off for: "+a};_.N[18]=MSGFUNC_TURN_OFF_FOR;MSG_ALWAYS_HIDE_AUTO_POPUP_BANNER="Always hide";_.N[19]=MSG_ALWAYS_HIDE_AUTO_POPUP_BANNER;MSG_ORIGINAL_TEXT="Original text:";_.N[20]=MSG_ORIGINAL_TEXT;MSG_FILL_SUGGESTION="Contribute a better translation";_.N[21]=MSG_FILL_SUGGESTION;
MSG_SUBMIT_SUGGESTION="Contribute";_.N[22]=MSG_SUBMIT_SUGGESTION;MSG_SHOW_TRANSLATE_ALL="Translate all";_.N[23]=MSG_SHOW_TRANSLATE_ALL;MSG_SHOW_RESTORE_ALL="Restore all";_.N[24]=MSG_SHOW_RESTORE_ALL;MSG_SHOW_CANCEL_ALL="Cancel all";_.N[25]=MSG_SHOW_CANCEL_ALL;MSG_TRANSLATE_TO_MY_LANGUAGE="Translate sections to my language";_.N[26]=MSG_TRANSLATE_TO_MY_LANGUAGE;MSGFUNC_TRANSLATE_EVERYTHING_TO=function(a){return"Translate everything to "+a};_.N[27]=MSGFUNC_TRANSLATE_EVERYTHING_TO;
MSG_SHOW_ORIGINAL_LANGUAGES="Show original languages";_.N[28]=MSG_SHOW_ORIGINAL_LANGUAGES;MSG_OPTIONS="Options";_.N[29]=MSG_OPTIONS;MSG_TURN_OFF_TRANSLATION_FOR_THIS_SITE="Turn off translation for this site";_.N[30]=MSG_TURN_OFF_TRANSLATION_FOR_THIS_SITE;_.N[31]=null;MSG_ALT_SUGGESTION="Show alternative translations";_.N[32]=MSG_ALT_SUGGESTION;MSG_ALT_ACTIVITY_HELPER_TEXT="Click words above to get alternative translations";_.N[33]=MSG_ALT_ACTIVITY_HELPER_TEXT;MSG_USE_ALTERNATIVES="Use";_.N[34]=MSG_USE_ALTERNATIVES;
MSG_DRAG_TIP="Drag with shift key to reorder";_.N[35]=MSG_DRAG_TIP;MSG_CLICK_FOR_ALT="Click for alternative translations";_.N[36]=MSG_CLICK_FOR_ALT;MSG_DRAG_INSTUCTIONS="Hold down the shift key, click and drag the words above to reorder.";_.N[37]=MSG_DRAG_INSTUCTIONS;MSG_SUGGESTION_SUBMITTED="Thank you for contributing your translation suggestion to Google Translate.";_.N[38]=MSG_SUGGESTION_SUBMITTED;MSG_MANAGE_TRANSLATION_FOR_THIS_SITE="Manage translation for this site";_.N[39]=MSG_MANAGE_TRANSLATION_FOR_THIS_SITE;
MSG_ALT_AND_CONTRIBUTE_ACTIVITY_HELPER_TEXT="Click a word for alternative translations or double-click to edit directly";_.N[40]=MSG_ALT_AND_CONTRIBUTE_ACTIVITY_HELPER_TEXT;MSG_ORIGINAL_TEXT_NO_COLON="Original text";_.N[41]=MSG_ORIGINAL_TEXT_NO_COLON;_.N[42]="Translate";_.N[43]="Translate";_.N[44]="Your correction has been submitted.";MSG_LANGUAGE_UNSUPPORTED="Error: The language of the web page is not supported.";_.N[45]=MSG_LANGUAGE_UNSUPPORTED;MSG_LANGUAGE_TRANSLATE_WIDGET="Language Translate Widget";
_.N[46]=MSG_LANGUAGE_TRANSLATE_WIDGET;MSG_RATE_THIS_TRANSLATION="Rate this translation";_.N[47]=MSG_RATE_THIS_TRANSLATION;MSG_FEEDBACK_USAGE_FOR_IMPROVEMENT="Your feedback will be used to help improve Google Translate";_.N[48]=MSG_FEEDBACK_USAGE_FOR_IMPROVEMENT;MSG_FEEDBACK_SATISFIED_LABEL="Good translation";_.N[49]=MSG_FEEDBACK_SATISFIED_LABEL;MSG_FEEDBACK_DISSATISFIED_LABEL="Poor translation";_.N[50]=MSG_FEEDBACK_DISSATISFIED_LABEL;MSG_TRANSLATION_NO_COLON="Translation";_.N[51]=MSG_TRANSLATION_NO_COLON;
}catch(e){_._DumpException(e)}
try{
_.ka("el_conf");
var yl;_._exportVersion=function(a){_.Tb("google.translate.v",a)};_._getCallbackFunction=function(a){return _.Lb(a)};_._exportMessages=function(){_.Tb("google.translate.m",_.N)};yl=function(a){var b=document.getElementsByTagName("head")[0];b||(b=document.body.parentNode.appendChild(document.createElement("head")));b.appendChild(a)};_._loadJs=function(a){var b=_.cd(document,"SCRIPT");b.type="text/javascript";b.charset="UTF-8";_.Ua(b,_.mb(a));yl(b)};
_._loadCss=function(a){var b=document.createElement("link");b.type="text/css";b.rel="stylesheet";b.charset="UTF-8";b.href=a;yl(b)};_._isNS=function(a){a=a.split(".");for(var b=window,c=0;c<a.length;++c)if(!(b=b[a[c]]))return!1;return!0};_._setupNS=function(a){a=a.split(".");for(var b=window,c=0;c<a.length;++c)b.hasOwnProperty?b.hasOwnProperty(a[c])?b=b[a[c]]:b=b[a[c]]={}:b=b[a[c]]||(b[a[c]]={});return b};_.Tb("_exportVersion",_._exportVersion);_.Tb("_getCallbackFunction",_._getCallbackFunction);
_.Tb("_exportMessages",_._exportMessages);_.Tb("_loadJs",_._loadJs);_.Tb("_loadCss",_._loadCss);_.Tb("_isNS",_._isNS);_.Tb("_setupNS",_._setupNS);window.addEventListener&&typeof document.readyState=="undefined"&&window.addEventListener("DOMContentLoaded",function(){document.readyState="complete"},!1);
_.ma();
}catch(e){_._DumpException(e)}
}).call(this,this.default_tr);
// Google Inc.

//# sourceURL=/_/translate_http/_/js/k=translate_http.tr.en_GB._AaUZ5ed64Q.O/am=BgM/d=1/rs=AN8SPfrLvBwl62cJIL256TkXGkB6rjLKMg/m=el_conf
    // Configure Constants
    (function(){
      let gtConstEvalStartTime = new Date();
      if (_isNS('google.translate.Element')){return}

      (function(){
        const c=_setupNS('google.translate._const');

        c._cest = gtConstEvalStartTime;
        gtConstEvalStartTime = undefined; // hide this eval start time constant
  c._cl='en-GB'; c._cuc='googleTranslateElementInit'; c._cac=''; c._cam=''; c._cenv='prod'; c._cll='INFO'; c._ctkk='482338.3166954629'; const h='translate.googleapis.com'; const oph='translate-pa.googleapis.com'; const s='https'+'://'; c._pah=h; c._pas=s; const b=s+'translate.googleapis.com'; const staticPath = '/translate_static/'; c._pci=b+staticPath+'img/te_ctrl3.gif'; c._pmi=b+staticPath+'img/mini_google.png'; c._pbi=b+staticPath+'img/te_bk.gif'; c._pli=b+staticPath+'img/loading.gif'; c._ps='https:\/\/www.gstatic.com\/_\/translate_http\/_\/ss\/k\x3dtranslate_http.tr.26tY-h6gH9w.L.W.O\/am\x3dBgM\/d\x3d0\/rs\x3dAN8SPfowrRiAotkQD9r4k3ANeQYGsCLZ7g\/m\x3del_main_css'; c._plla=oph+'\/v1\/supportedLanguages'; c._puh='translate.google.com';c._cnal={};_loadCss(c._ps); _loadJs('https:\/\/translate.googleapis.com\/_\/translate_http\/_\/js\/k\x3dtranslate_http.tr.en_GB._AaUZ5ed64Q.O\/am\x3dABA\/d\x3d1\/exm\x3del_conf\/ed\x3d1\/rs\x3dAN8SPfpTzeWsOTewTI2DGvpR7Tb8gE8jUA\/m\x3del_main');_exportMessages(); _exportVersion('TE_20250107');
        })();
      })();
  